---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: no-op
spec:
  name: no-op
  protocol: http
  active: true
  proxy:
    target_url: http://httpbingo.org
    listen_path: /no-op
    strip_listen_path: true
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: no-op
spec:
  name: no-op
  state: active
  active: true
  access_rights_array:
    - name: no-op
      namespace: tyk
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-jwt
spec:
  name: httpbin-jwt
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin-svc.tyk.svc:8000
    listen_path: /httpbin-jwt
    strip_listen_path: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: http://keycloak-service.tyk.svc:7000/realms/keycloak-oauth/protocol/openid-connect/certs
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - tyk/no-op
  jwt_scope_claim_name: group
  jwt_scope_to_policy_mapping:
    admins: tyk/httpbin-admins
    developers: tyk/httpbin-developers
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-admins
spec:
  name: httpbin-admins
  state: active
  active: true
  access_rights_array:
    - name: httpbin-jwt
      namespace: tyk
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-developers
spec:
  name: httpbin-developers
  state: active
  active: true
  access_rights_array:
    - name: httpbin-jwt
      namespace: tyk
      versions:
        - Default
      allowed_urls:
        - url: /xml
          methods:
            - GET